#pragma checksum "..\..\Activity3.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "F7D71B20CF1919FA16A23C317C875BAAB345DAAE0BE62EA6D6F757EF499F5027"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newproject;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Newproject {
    
    
    /// <summary>
    /// Activity3
    /// </summary>
    public partial class Activity3 : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label word3;
        
        #line default
        #line hidden
        
        
        #line 11 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OK1;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Lscorec;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label Lscorei;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Timer;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button back;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image bi1;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image bi2;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image bi3;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button bo1;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button bo2;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button bo3;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image yay;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\Activity3.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button start;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Newproject;component/activity3.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\Activity3.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.word3 = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.OK1 = ((System.Windows.Controls.Button)(target));
            
            #line 11 "..\..\Activity3.xaml"
            this.OK1.Click += new System.Windows.RoutedEventHandler(this.OK1_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.Lscorec = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.Lscorei = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.Timer = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.back = ((System.Windows.Controls.Button)(target));
            
            #line 15 "..\..\Activity3.xaml"
            this.back.Click += new System.Windows.RoutedEventHandler(this.back_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.bi1 = ((System.Windows.Controls.Image)(target));
            return;
            case 8:
            this.bi2 = ((System.Windows.Controls.Image)(target));
            return;
            case 9:
            this.bi3 = ((System.Windows.Controls.Image)(target));
            return;
            case 10:
            this.bo1 = ((System.Windows.Controls.Button)(target));
            
            #line 23 "..\..\Activity3.xaml"
            this.bo1.Click += new System.Windows.RoutedEventHandler(this.bo1_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.bo2 = ((System.Windows.Controls.Button)(target));
            
            #line 24 "..\..\Activity3.xaml"
            this.bo2.Click += new System.Windows.RoutedEventHandler(this.bo2_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.bo3 = ((System.Windows.Controls.Button)(target));
            
            #line 25 "..\..\Activity3.xaml"
            this.bo3.Click += new System.Windows.RoutedEventHandler(this.bo3_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.yay = ((System.Windows.Controls.Image)(target));
            return;
            case 14:
            this.start = ((System.Windows.Controls.Button)(target));
            
            #line 27 "..\..\Activity3.xaml"
            this.start.Click += new System.Windows.RoutedEventHandler(this.start_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

